### ISSUE TITLE
Bonjour, je suis un gentil contributeur et j'aimerais contribuer avec un article sur le cheval

### ISSUE THREAD

**Issue by BlackMouse** [Youpssitech-Yournal/Yournal#1]
Voila mon article, j'espère qu'il sera ajouté :)
[Histoire_du_petit_cheval_vert_(texte).pdf](https://github.com/Youpssitech-Yournal/Yournal/files/211817/Histoire_du_petit_cheval_vert_.texte.pdf)

**Comment by kloumpt** [comment]
Excusez moi mon brave, mais le Yournal ne comporte toujours pas de rubrique histoires, il ne sera donc pas possible d'ajouter votre contribution à la prochaine édition :)
